### ISSUE TITLE
Cannot read property 'moduleFileExtensions' of undefined

### ISSUE THREAD

**Issue by leegee** [ziad-saab/babel-jest-require-ensure#2]
```
 ● Test suite failed to run

    TypeError: Cannot read property 'moduleFileExtensions' of undefined

       5 | module.exports = {
       6 |   process: function(src, filename) {
    >  7 |     var processed = babelJest.process(src, filename)
         |                               ^
       8 |         .replace(/require\(\s*'[a-zA-Z0-9\/\._\-!]*\.(css|scss|less)'\);/gm, '');
       9 |
      10 |     if (processed.match(/require\.ensure\(/) && !processed.match(/require\.ensure =/))

      at Object.process (node_modules/babel-jest/build/index.js:153:30)
      at Object.process (tests/jest-babel-custom.js:7:31)


[landing-pages 09:07]$ jest --version
22.4.3
[landing-pages 09:07]$ webpack --version
4.6.0
grep babel-core package.json
    "babel-core": "^6.26.3",
```

**Comment by ifgeny87** [comment]
I think it helps
https://github.com/facebook/jest/issues/5185
